document.getElementById("botao1").textContent = "Home";
document.getElementById("botao2").textContent = "Queijo";
document.getElementById("botao3").textContent = "Goiaba";
document.getElementById("botao4").textContent = "Surucucu";
document.getElementById("email").placeholder = "Digita o email ae irmão";
document.getElementById("senha").placeholder = "Senha tbm po";
document.getElementById("div1").style.borderColor = "yellow";
document.getElementById("div1").style.borderRadius = "40px";
document.getElementById("navbar").style.backgroundColor = "blue";